Repository hlakudi200/hris-repo, pull requests merged in 2025-04, with the labels that each got.

#98 Lihlumise/bug/loading leaves
  hris/src/_componets/leaveOverviewComponent/leaveOverview.tsx
Labels: bug

#104 Lihlumise/feature/leave page
  aspnet-core/src/hrisApi.EntityFrameworkCore/EntityFrameworkCore/hrisApiDbContext.cs
  hris/src/_componets/globals.module.css
  hris/src/_componets/leaveFormComponet/leaveForm.tsx
  hris/src/_componets/leaveOverviewComponent/leaveOverview.tsx
  hris/src/app/employee/leave/page.tsx
  hris/src/app/employee/leave/styles/global.module.css
  hris/src/providers/employee/index.tsx
  hris/src/providers/leaveRequest/actions.tsx
  hris/src/providers/leaveRequest/context.tsx
  hris/src/providers/leaveRequest/index.tsx
  hris/src/providers/leaveRequest/reducer.tsx
Labels: enhancement

#111 Tax Calculation
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/DTO/PayrollProfileDto.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollTransactionService/DTO/PayrollTransactionDto.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollTransactionService/IPayrollTransactionAppService.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollTransactionService/PayrollTransactionAppService.cs
Labels: enhancement

#113 Making Validation on Gross Amount
  aspnet-core/src/hrisApi.Application/Services/PayrollTransactionService/PayrollTransactionAppService.cs
Labels: bug

#114 Lihlumise/feature/log hours/provider connection
  aspnet-core/src/hrisApi.Application/Services/ProjectService/DTO/ProjectDto.cs
  hris/src/_componets/attandaceComponent/attandanceOverview.tsx
  hris/src/_componets/attandanceFormComponent/attandanceForm.tsx
  hris/src/providers/attandance/context.tsx
  hris/src/providers/attandance/index.tsx
Labels: enhancement

#120 Lihlumise/feature/internal job application
  hris/src/_componets/JobPostComponent/jobPostComponent.tsx
Labels: enhancement

#128 Updated formatting
  hris/src/_componets/attandanceFormComponent/attandanceForm.tsx
  hris/src/_componets/fileUploadComponent/fileUpload.tsx
  hris/src/_componets/jobApplicationFormComponent/jobApplicationForm.tsx
  hris/src/_componets/leaveFormComponent/leaveForm.tsx
  hris/src/_componets/leaveOverviewComponent/leaveOverview.tsx
  hris/src/_componets/profileComponent/profile.tsx
  hris/src/app/auth/login/page.tsx
  hris/src/app/employee/leave/page.tsx
  hris/src/app/employee/page.tsx
  hris/src/app/hoc/withAuth.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/providers/attandance/actions.tsx
  hris/src/providers/attandance/context.tsx
  hris/src/providers/attandance/reducer.tsx
  hris/src/providers/jobApplication/reducer.tsx
  hris/src/providers/jobPost/context.tsx
  hris/src/providers/jobPost/index.tsx
  hris/src/providers/jobPost/interfaces.ts
  hris/src/providers/jobPost/reducer.tsx
  hris/src/providers/leaveRequest/index.tsx
  hris/src/providers/payrolltransaction/index.tsx
Labels: enhancement

#131 Updated migrations
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411070128_Dbsets.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411070128_Dbsets.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411103039_PorjectModal.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411103039_PorjectModal.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411133808_update-Attandance.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411133808_update-Attandance.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411135044_AttandaceProp.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411135044_AttandaceProp.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411143649_chnagedtoTimeSpan.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411143649_chnagedtoTimeSpan.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411144116_chnagedtoString.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411144116_chnagedtoString.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411144956_chnagedtoString2.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250411144956_chnagedtoString2.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250412012612_updatedProps.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250412012612_updatedProps.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250415100133_Update-Database.Designer.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/20250415100133_Update-Database.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/hrisApiDbContextModelSnapshot.cs
Labels: enhancement

#136 Tr/bug/resolve package
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/DTO/PayrollProfileDto.cs
  hris/package.json
  hris/src/_componets/hrCharts/hrChart.tsx
  hris/src/_componets/hrCharts/styles/styles.module.css
  hris/src/app/hrManager/layout.tsx
  hris/src/app/hrManager/page.tsx
  hris/src/app/hrManager/styles/global.module.css
  hris/src/providers/attandance/actions.tsx
  hris/src/providers/payrolltransaction/actions.tsx
  hris/src/providers/payrolltransaction/context.tsx
  hris/src/providers/payrolltransaction/index.tsx
  hris/src/providers/payrolltransaction/reducer.tsx
Labels: enhancement

#133 Lihlumise/feaute/hr manager routing
  hris/src/app/employee/layout.tsx
  hris/src/app/hrManager/employees/page.tsx
  hris/src/app/hrManager/interviews/page.tsx
  hris/src/app/hrManager/jobPost/page.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/app/hrManager/payroll/page.tsx
  hris/src/app/hrManager/projects/page.tsx
Labels: enhancement

#145 View All Applications Component
  aspnet-core/src/hrisApi.Application/Services/JobApplicationService/DTO/JobApplicationDto.cs
  aspnet-core/src/hrisApi.Application/Services/JobPostingService/DTO/JobPostingDto.cs
  aspnet-core/src/hrisApi.Core/Domains/Recruitment Module/JobApplication.cs
  aspnet-core/src/hrisApi.EntityFrameworkCore/Migrations/hrisApiDbContextModelSnapshot.cs
  hris/src/_componets/projects/projects.tsx
  hris/src/_componets/viewJobApplications/viewJobApplications.tsx
  hris/src/app/hrManager/jobApplications/page.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/app/hrManager/projects/page.tsx
  hris/src/providers/attandance/actions.tsx
  hris/src/providers/attandance/context.tsx
  hris/src/providers/attandance/index.tsx
  hris/src/providers/attandance/reducer.tsx
  hris/src/providers/jobApplication/actions.tsx
  hris/src/providers/jobApplication/context.tsx
  hris/src/providers/jobApplication/index.tsx
  hris/src/providers/jobApplication/reducer.tsx
Labels: enhancement

#154 Lihlumise/feature/role based redirection
  aspnet-core/src/hrisApi.Core/Domains/Employee Management/EmployeeManager.cs
  hris/package.json
  hris/src/app/auth/login/page.tsx
  hris/src/providers/auth/actions.tsx
  hris/src/providers/auth/context.tsx
  hris/src/providers/auth/index.tsx
  hris/src/providers/auth/reducer.tsx
  hris/src/utils/jwtDecoder.ts
Labels: enhancement

#159 Interview UI
  hris/src/app/hrManager/interview/page.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/providers/Interview/actions.tsx
  hris/src/providers/Interview/context.tsx
  hris/src/providers/Interview/index.tsx
  hris/src/providers/Interview/reducer.tsx
Labels: enhancement

#164 Lihlumise/feature/Applicant sign up
  aspnet-core/src/hrisApi.Application/Services/ApplicantService/ApplicantAppService.cs
  aspnet-core/src/hrisApi.Application/Services/ApplicantService/IApplicantAppService.cs
  hris/src/app/auth/signup/page.tsx
  hris/src/providers/auth/index.tsx
Labels: enhancement

#160 Lihlumise/feature/hr manager payroll
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/DTO/NamedPayrollProfileDto.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/IPayrollProfileAppService.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/PayrollProfileAppService.cs
  hris/src/_componets/managerPayroll/managerPayroll.tsx
  hris/src/_componets/viewPayrollTransactions/viewPayrollTransactions.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/app/hrManager/payroll/page.tsx
  hris/src/providers/payrollProfile/actions.tsx
  hris/src/providers/payrollProfile/context.tsx
  hris/src/providers/payrollProfile/index.tsx
  hris/src/providers/payrollProfile/reducer.tsx
Labels: enhancement

#162 GetAllEmployees Endpoint
  aspnet-core/src/hrisApi.Application/Services/Employee Management/DTO/PagedEmployeeResultrequestDto.cs
  aspnet-core/src/hrisApi.Application/Services/Employee Management/EmployeeAppService.cs
  aspnet-core/src/hrisApi.Application/Services/InterviewService/InterviewAppService.cs
  aspnet-core/src/hrisApi.Core/Domains/Employee Management/EmployeeManager.cs
Labels: enhancement

#165 Motseki/enhancement/get all employees view fixed
  hris/src/_componets/createEmployee/page.tsx
  hris/src/app/hrManager/employees/page.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/providers/employee/actions.tsx
  hris/src/providers/employee/context.tsx
  hris/src/providers/employee/index.tsx
  hris/src/providers/employee/reducer.tsx
  hris/src/utils/axios-instance.tsx
Labels: enhancement

#163 ViewEmployees Component
  hris/src/_componets/createEmployee/page.tsx
  hris/src/app/hrManager/employees/page.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/providers/employee/actions.tsx
  hris/src/providers/employee/context.tsx
  hris/src/providers/employee/index.tsx
  hris/src/providers/employee/reducer.tsx
  hris/src/utils/axios-instance.tsx
Labels: enhancement

#170 Lihlumise/feature/employee sign out
  hris/src/app/employee/layout.tsx
  hris/src/app/employee/styles/global.module.css
  hris/src/app/hrManager/layout.tsx
  hris/src/app/hrManager/styles/global.module.css
  hris/src/providers/auth/actions.tsx
  hris/src/providers/auth/context.tsx
  hris/src/providers/auth/index.tsx
  hris/src/providers/auth/reducer.tsx
Labels: enhancement

#171 Spinner Loaders for Employee
  hris/src/_componets/createEmployee/page.tsx
  hris/src/_componets/profileComponent/profile.tsx
Labels: enhancement

#176 Subtracting leave days after application
  hris/src/_componets/leaveFormComponent/leaveForm.tsx
  hris/src/app/employee/leave/styles/global.module.css
  hris/src/providers/employee/actions.tsx
  hris/src/providers/employee/context.tsx
  hris/src/providers/employee/index.tsx
  hris/src/providers/employee/reducer.tsx
  hris/src/utils/subtractLeaves.ts
Labels: enhancement

#181 Lihlumise/feature/leave calendar
  hris/package.json
  hris/src/_componets/leaveCalendar/leaveCalendar.tsx
  hris/src/app/employee/logHours/page.tsx
  hris/src/app/employee/page.tsx
Labels: enhancement

#189 Lihlumise/feature/payroll leave creation
  aspnet-core/src/hrisApi.Core/Domains/Employee Management/EmployeeManager.cs
  hris/src/_componets/payrollComponent/employeePayroll.tsx
Labels: enhancement

#195 filters on job applications and uses email provider actions
  hris/src/_componets/viewJobApplications/viewJobApplications.tsx
  hris/src/providers/email/emailTemplates/approveApplication.ts
  hris/src/providers/email/emailTemplates/declineApplication.ts
  hris/src/providers/jobApplication/context.tsx
  hris/src/providers/jobPost/interfaces.ts
Labels: enhancement

#196 Added leave request data on HR Dashboard
  hris/src/_componets/hrCharts/hrChart.tsx
  hris/src/_componets/hrCharts/styles/styles.module.css
Labels: enhancement

#190 Schedule Interview Via JobId
  hris/src/_componets/interviewComponent/page.tsx
  hris/src/providers/jobApplication/actions.tsx
  hris/src/providers/jobApplication/context.tsx
  hris/src/providers/jobApplication/index.tsx
  hris/src/providers/jobApplication/reducer.tsx
Labels: enhancement

#198 Sending emails to employees upon registeration
  aspnet-core/src/hrisApi.Application/Services/Employee Management/EmployeeAppService.cs
Labels: enhancement

#200 Lihlumise/feature/applicant job view
  hris/src/_componets/applicantJobView/applicantJobView.tsx
  hris/src/_componets/fileUploadComponent/fileUpload.tsx
  hris/src/app/applicant/layout.tsx
  hris/src/app/applicant/page.tsx
  hris/src/app/applicant/styles/global.module.css
Labels: enhancement

#201 Fixed typo
  hris/src/providers/jobApplication/actions.tsx
Labels: bug

#211 Added login page unit test
  hris/src/_componets/JobPostComponent/__tests__/jobPostComponent.test.tsx
  hris/src/app/auth/login/__tests__/page.test.tsx
Labels: enhancement

#217 Rapudi/feature/saveresume
  hris/next.config.ts
  hris/package.json
  hris/src/_componets/applicantJobView/applicantJobView.tsx
  hris/src/_componets/fileUploadComponent/fileUpload.tsx
  hris/src/providers/email/emailTemplates/applicationSubmitted.ts
  hris/src/providers/jobApplication/actions.tsx
  hris/src/providers/jobApplication/context.tsx
  hris/src/providers/jobApplication/index.tsx
  hris/src/providers/jobApplication/reducer.tsx
  hris/src/utils/supabaseClient.ts
Labels: enhancement

#215 Added initial readme file for the front end
  hris/README.md
Labels: documentation

#218 Cleanrepo
  .vs/hris-repo/CopilotIndices/17.12.53.23981/CodeChunks.db
  .vs/hris-repo/CopilotIndices/17.12.53.23981/SemanticSymbols.db
  .vs/hris-repo/v17/.wsuo
  .vs/hris-repo/v17/DocumentLayout.json
  .vs/hris-repo/v17/TestStore/0/000.testlog
  .vs/hris-repo/v17/TestStore/0/testlog.manifest
  hris/src/_componets/createJobPost/createJobPost.tsx
  hris/src/_componets/fileUploadComponent/fileUpload.tsx
  hris/src/_componets/interviewComponent/page.tsx
  hris/src/_componets/interviewComponent/styles/styles.module.css
  hris/src/_componets/projects/projects.tsx
  hris/src/_componets/viewPayrollTransactions/viewPayrollTransactions.tsx
  hris/src/providers/attandance/index.tsx
  hris/src/providers/jobApplication/index.tsx
  hris/src/providers/jobPost/index.tsx
  hris/src/providers/leaveRequest/index.tsx
  hris/src/providers/payrollProfile/index.tsx
  hris/src/providers/payrolltransaction/index.tsx
Labels: enhancement

#223 Changed from post to put method for updating leaves
  hris/src/providers/leaves/index.tsx
Labels: bug

#228 Hr Ai chat bot
  hris/src/_componets/hrchatbot/chatbot.tsx
  hris/src/_componets/interviewComponent/styles/styles.module.css
  hris/src/app/hrManager/layout.tsx
  hris/src/app/hrManager/page.tsx
Labels: enhancement

#227 Updated useEffect
  hris/src/_componets/profileComponent/profile.tsx
Labels: bug

#229 entire read me
  README.md
Labels: enhancement

#236 Lihlumise/feature/endpoint auth
  aspnet-core/src/hrisApi.Application/Services/AbsenceReportService/AbsenceReportAppService.cs
  aspnet-core/src/hrisApi.Application/Services/ApplicantService/ApplicantAppService.cs
  aspnet-core/src/hrisApi.Application/Services/AttendaceRecordService/AttendanceRecordAppService.cs
  aspnet-core/src/hrisApi.Application/Services/BonusOrCommissionService/BonusOrCommissionAppService.cs
  aspnet-core/src/hrisApi.Application/Services/Employee Management/DTO/CreateEmployeeDto.cs
  aspnet-core/src/hrisApi.Application/Services/Employee Management/EmployeeAppService.cs
  aspnet-core/src/hrisApi.Application/Services/Employee Management/Helpers/PasswordGenerator.cs
  aspnet-core/src/hrisApi.Application/Services/InterviewService/InterviewAppService.cs
  aspnet-core/src/hrisApi.Application/Services/JobApplicationService/JobApplicationAppService.cs
  aspnet-core/src/hrisApi.Application/Services/JobPostingService/JobPostingAppService.cs
  aspnet-core/src/hrisApi.Application/Services/LeaveRequestService/LeaveRequestAppService.cs
  aspnet-core/src/hrisApi.Application/Services/LeaveService/LeaveAppService.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/PayrollProfileAppService.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollTransactionService/PayrollTransactionAppService.cs
  aspnet-core/src/hrisApi.Application/Services/ProjectService/ProjectAppService.cs
  aspnet-core/src/hrisApi.Core/Domains/Employee Management/EmployeeManager.cs
  hris/src/_componets/createEmployee/page.tsx
  hris/src/providers/auth/index.tsx
  hris/src/providers/employee/context.tsx
  hris/src/utils/axios-instance.tsx
Labels: enhancement

#237 Search bar for employees
  hris/src/_componets/createEmployee/page.tsx
Labels: enhancement

#242 Fetching user information after browser information
  hris/src/providers/auth/index.tsx
Labels: enhancement

#238 Lihlumise/feature/hoc
  aspnet-core/src/hrisApi.Application/Services/ApplicantService/ApplicantAppService.cs
  hris/src/app/applicant/layout.tsx
  hris/src/app/employee/layout.tsx
  hris/src/app/hoc/withAuth.tsx
  hris/src/app/hrManager/layout.tsx
Labels: enhancement

#244 Lihlumise/feauture/employee salary
  aspnet-core/src/hrisApi.Application/Services/Employee Management/DTO/CreateEmployeeDto.cs
  aspnet-core/src/hrisApi.Application/Services/Employee Management/EmployeeAppService.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/DTO/GetPayrollProfileDto.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/PayrollProfileAppService.cs
  aspnet-core/src/hrisApi.Core/Domains/Employee Management/EmployeeManager.cs
  aspnet-core/src/hrisApi.Core/Domains/Employee Management/Helpers/TaxCalculator.cs
  hris/src/_componets/createEmployee/page.tsx
  hris/src/app/favicon.ico
  hris/src/app/layout.tsx
  hris/src/providers/employee/context.tsx
Labels: enhancement

#247 Lihlumise/bug/leave manipulation
  hris/src/_componets/createEmployee/page.tsx
  hris/src/_componets/interviewComponent/page.tsx
  hris/src/_componets/leaveFormComponent/leaveForm.tsx
  hris/src/_componets/manageLeaveRequests/manageLeaveRequest.tsx
  hris/src/app/hrManager/layout.tsx
  hris/src/providers/employee/index.tsx
  hris/src/providers/leaves/actions.tsx
  hris/src/providers/leaves/context.tsx
  hris/src/providers/leaves/index.tsx
  hris/src/providers/leaves/reducer.tsx
  hris/src/utils/subtractLeaves.ts
Labels: bug

#250 Lihlumise/feature/overview state
  hris/src/_componets/attandaceComponent/attandanceOverview.tsx
  hris/src/_componets/leaveCalendar/leaveCalendar.tsx
  hris/src/app/employee/logHours/page.tsx
  hris/src/app/employee/page.tsx
  hris/src/providers/attandance/index.tsx
Labels: enhancement

#251 Rapudi/view applied jobs
  aspnet-core/src/hrisApi.Application/Services/Employee Management/EmployeeAppService.cs
  aspnet-core/src/hrisApi.Application/Services/LeaveRequestService/LeaveRequestAppService.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollProfileService/PayrollProfileAppService.cs
  aspnet-core/src/hrisApi.Application/Services/PayrollTransactionService/PayrollTransactionAppService.cs
  aspnet-core/test/hrisApi.Tests/Services/PayrollTransaction/PayrollTransactionAppServiceTests.cs
  hris/src/_componets/applicantJobView/applicantJobView.tsx
  hris/src/_componets/applicantProfile/applicantProfile.tsx
  hris/src/_componets/application/completeForm/jobApplicationForm.tsx
  hris/src/_componets/application/completeForm/styles/styles.module.css
  hris/src/_componets/createJobApplicationPorfile/createJobPorfile.tsx
  hris/src/_componets/createJobApplicationPorfile/styles/styles.module.css
  hris/src/_componets/trackJobApplications/trackJobApplications.tsx
  hris/src/app/applicant/applications/page.tsx
  hris/src/app/applicant/createProfile/page.tsx
  hris/src/app/applicant/interviews/page.tsx
  hris/src/app/applicant/layout.tsx
  hris/src/app/applicant/page.tsx
  hris/src/app/applicant/profile/page.tsx
  hris/src/providers/jobApplicant/actions.tsx
  hris/src/providers/jobApplicant/index.tsx
  hris/src/providers/jobApplication/context.tsx
  hris/src/providers/payrolltransaction/index.tsx
  hris/src/utils/axios-instance.tsx
  hris/src/utils/supabaseClient.ts
Labels: enhancement

#255 Added password input validation
  hris/src/app/auth/signup/page.tsx
Labels: bug

#256 Lihlumise/feature/username validation
  aspnet-core/src/hrisApi.Application/Services/ApplicantService/ApplicantAppService.cs
  hris/src/_componets/applicantProfile/applicantProfile.tsx
  hris/src/app/auth/signup/page.tsx
  hris/src/providers/auth/index.tsx
Labels: enhancement

#257 Displaying different colours on leave calender based on request status
  hris/src/_componets/leaveCalendar/leaveCalendar.tsx
  hris/src/providers/leaveRequest/index.tsx
Labels: enhancement
